/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Nike.gltf 
Author: uv15o6 (https://sketchfab.com/uv15o6)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/nike-shoe-73501460b48b4e579d18cfab23c0f605
Title: Nike Shoe
*/

import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Nike.gltf')
  return (
    <group {...props} dispose={null}  scale={0.5} position={[0,-1.3,0]}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.defaultMat} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.defaultMat} />
    </group>
  )
}

useGLTF.preload('/Nike.gltf')
