/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 shoes.gltf 
Author: Ronen (https://sketchfab.com/ronenh)
License: CC-BY-ND-4.0 (http://creativecommons.org/licenses/by-nd/4.0/)
Source: https://sketchfab.com/3d-models/saucony-endorphin-shift-e343bd847b244f0da17f3e873333c7a3
Title: Saucony Endorphin Shift
*/

// import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoes.gltf')
  return (
    <group {...props} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.material0} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material0} />
      </group>
    </group>
  )
}

useGLTF.preload('/shoes.gltf')
