/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Vans.gltf 
Author: Lassi Kaukonen (https://sketchfab.com/thesidekick)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unused-blue-vans-shoe-96baa4684df7415ba8ba87d39bd1c2ee
Title: Unused Blue Vans Shoe
*/

import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Vans.gltf')
  return (
    <group {...props} dispose={null} scale={0.7} position={[0, -1.3, 1]}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Blue_Vans_Shoe} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Vans.gltf')
